### ISSUE TITLE
Issue with smtp_content_filter parameter

### ISSUE THREAD

**Issue by kg4zow** [thias/puppet-postfix#32]
Trying to use the module as part of a larger class which configures postfix to send outbound email. My wrapper class looks like this:

```
class client_postfix {
  class { '::postfix::server' :
    myorigin => 'client.net' ,
  }
}
```

When I try to use this module, the agent reports the following error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Undefined variable "smtp_content_filter" at /etc/puppet/modules/postfix/manifests/server.pp:79 on node sandbox.client.net
```

Looking at the module itself...

```
     77   # master.cf
     78   $smtp_content_filter = [],
     79   $smtps_content_filter = $smtp_content_filter,
     80   $submission = false,
```

I've never seen a puppet module use one parameter as the default value for another parameter like this. Is this something which Puppet previously supported, but was removed? (I'm using Puppet 3.6.2 from the Puppetlabs RPMs, on CentOS 6.)

**Comment by wyrie** [comment]
I'm hitting this issue too, please merge.

**Comment by thias** [comment]
Thanks! And sorry for the delay. I think this was incorrect from the start, but in my testing environments I have the `$smtps_content_filter` parameter set explicitly, so I didn't catch the error.

**Comment by kaihowl** [comment]
Is there any date for the next release on forge that will include this fix?
