### ISSUE TITLE
smtp_tls_security_level

### ISSUE THREAD

**Issue by sbpaul** [thias/puppet-postfix#36]
Hi,

the smtp_tls_security_level is a seperate config parameter and has not a requirement of sasl

correct parts of the main.cf.erb
========

<% if @smtp_sasl_auth -%>
# Client auth against SMTP gateway
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = <%= @smtp_sasl_password_maps %>
smtp_sasl_security_options = <%= @smtp_sasl_security_options %>
<% if @smtp_sasl_tls -%>
smtp_use_tls = yes
<% end -%>
<% end -%>

<% if @smtp_tls_CAfile -%>
smtp_tls_CAfile = <%= @smtp_tls_CAfile %>
<% end -%>
<% if @smtp_tls_CApath -%>
smtp_tls_CApath = <%= @smtp_tls_CApath %>
<% end -%>
<% if @smtp_tls_security_level -%>
smtp_tls_security_level = <%= @smtp_tls_security_level %>
<% end -%>

**Comment by loosi** [comment]
Its not a big deal to fix it, but its been some time since some commit - shall we just make a pull request?

**Comment by thias** [comment]
Yes, please! Pull requests make code easier to read than in unformatted text :-)

**Comment by thias** [comment]
I have just checked, and this has been in a block with `<% if @smtp_sasl_tls or @smtp_use_tls -%>` for a while now, so it should already be fixed.
