### ISSUE TITLE
Release 0.3.4

### ISSUE THREAD

**Issue by djjudas21** [thias/puppet-postfix#40]
Hi there,

Would you please consider making an updated release on Puppet Forge?

0.3.3 does not work on CentOS 7 and I suspect this is problematic for many people.

Thanks,
Jonathan

**Comment by sgran** [comment]
*bounce* :)

**Comment by djjudas21** [comment]
Hi, do you plan to make a release of the current code to the Forge? If not, I'll fork the module and maintain my own.

**Comment by djjudas21** [comment]
FYI https://forge.puppetlabs.com/jgazeley/postfix

**Comment by thias** [comment]
Wow, I can't believe I have taken so long to get this done! I'm really sorry...

As you can imagine, I have been using my own module from git this whole time.

I have now released 0.3.4 at last, and will be going through issue reports and pull requests shortly.
