### ISSUE TITLE
Debian support not documented

### ISSUE THREAD

**Issue by lingfish** [thias/puppet-postfix#54]
Hi, your params.pp seems to hint at Debian support, yet the README does not?

**Comment by thias** [comment]
The Forge page does mention both Ubuntu and Debian, since it takes the information from the metadata.json file. I don't personally use either, only Fedora and RHEL, so it might not be a bad thing the README doesn't mention them : They're clearly "second class" as their support has been contributed through pull requests and I'm not actively tracking and testing them.

**Comment by gwarf** [comment]
Hi, just a personal thought, we are using this module on debian (wheezy for the time being) and it is working as expected for our needs.
Documenting the support in the metadata.json (then in the forge) would also allow to gain more attention from people from the forge, meaning more users, meaning more PR to allow fixing potential problems or adding features, it might be interesting to go that way... :)
By the way thanks for this module!

**Comment by thias** [comment]
What I was saying is that it **does** show Ubuntu and Debian as being compatible on the forge page : https://forge.puppetlabs.com/thias/postfix ;-)

**Comment by gwarf** [comment]
Did I say something ? ;)

**Comment by lingfish** [comment]
Sorry, a little lost here. The Forge page says it, the module has it, so why not mentioned it/brag in the README as well?  By habit, that'd usually be the first place I'd look, rather than Forge.  I don't think that by @thias not using Debian means it isn't still supported and awesome on Debian! :)

I wouldn't say the support for it is "second class" -- contribs/pull requests are the key to Github/OSS stuff.  I too use it on Debian and it works great, and will happily supply PR's and whatnot ongoing to continue it's Debian-based support.
