### ISSUE TITLE
Doesn't cater for postalias requirement

### ISSUE THREAD

**Issue by lingfish** [thias/puppet-postfix#55]
The `aliases` file needs to be rebuilt upon refresh using either `newaliases`, or `postalias`, and not `postmap`.  I'd submit a pull, but there's a few ways to tackle it, and I don't know which would suit your project.

**Comment by thias** [comment]
I think this is beyond the scope of this module, and should be managed by the built-in `mailalias` type.

To work around this, I typically set something like this in my `site.pp` : 
```puppet
Mailalias {
  notify => Exec['newaliases'],
  target => '/etc/aliases',
}
exec { 'newaliases' :
  command     => '/usr/bin/newaliases',
  refreshonly => true,
}
```

AFAIK, a module can't set a default for built-in types at the top scope like the above does, unfortunately. If you still think it should be managed by my module, please reopen and provide your reasoning and a suggested way of tackling the problem :-)

**Comment by lingfish** [comment]
Heya, I disagree somewhat.

It would be fair to say that, at least, an `exec` should be provided by a postfix module, as each mailer package could (and usually does) have different ways of rebuilding the `aliases` database, agree?  It's then up to the user if they want to use it or not.

That's where it gets muddy... using the built-in `mailalias` type I agree with; but usually we'd have to write a wrapper around it to do `create_resources`... and do the aliases come from Hiera (a smart choice), or...

I kind of like what this person is doing: https://github.com/duritong/puppet-postfix/blob/master/manifests/mailalias.pp

**Comment by lingfish** [comment]
(Oh, and I can't re-open this, explained in http://stackoverflow.com/a/21333938/3926181 :) )

**Comment by lingfish** [comment]
Hi, no further thoughts on this?
