### ISSUE TITLE
versioncmp broken in RHEL/CentOS 7

### ISSUE THREAD

**Issue by idleyoungman** [thias/puppet-postfix#64]
```
==> default: Error: comparison of String with 6 failed at /tmp/vagrant-puppet-3/modules-1/postfix/manifests/server.pp:150 on node ...
```
Either #39 or #63 fix this by using the operatingsystemmajrelease fact instead of operatingsystemrelease (versioncmp chokes on '7.0.1406' in Centos 7.0).

**Comment by jovandeginste** [comment]
I think this is fixed with dcbd9f772a1dc8f686737f74c4895ee80ac6ed3a ?

**Comment by RXM307** [comment]
You could also use 
if ( $::operatingsystem =~ /RedHat|CentOS/ and $::operatingsystemmajrelease < 6 ) {

**Comment by ZhukV** [comment]
+1

**Comment by thias** [comment]
Forge release 0.3.4 includes the fix for this at last, sorry for the delay.
