### ISSUE TITLE
version not updated

### ISSUE THREAD

**Issue by jjolet** [thias/puppet-postfix#70]
The version on the forge is 0.3.3, and the Modulefile on github says 0.3.3, but the code is NOT the same.  there was an issue with comparing operatingsystemversion with 6 instead of '6' that is fixed on github, but that code isn't what gets pulled in from the forge.  Is there a way to fix this?  currently, i've repointed my r10k Puppetfile to github directly, but i'd prefer to pull from the forge.

**Comment by alexanderdavidsen** [comment]
+1

**Comment by aairey** [comment]
+1 for lint fixes made by @dwagon

**Comment by mrolli** [comment]
+1 Please make a new release! Do it, do it now! ;-)

**Comment by thias** [comment]
Forge release 0.3.4 includes the fix for this at last, sorry for the delay.
