### ISSUE TITLE
Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/postfix/header_checks20160105-7144-1n4vwk8.lock

### ISSUE THREAD

**Issue by eLvErDe** [thias/puppet-postfix#77]
Hello,

It seems there's a little dependency issue somewhere, at my first run I get these three errors in my foreman logs:

Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/postfix/header_checks20160105-7144-1n4vwk8.lock at 44:/etc/puppet/environments/production/modules/postfix/manifests/file.pp

Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/postfix/header_checks20160105-7144-1n4vwk8.lock at 44:/etc/puppet/environments/production/modules/postfix/manifests/file.pp Wrapped exception: No such file or directory @ dir_s_rmdir - /etc/postfix/header_checks20160105-7144-1n4vwk8.lock

change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/postfix/header_checks20160105-7144-1n4vwk8.lock at 44:/etc/puppet/environments/production/modules/postfix/manifests/file.pp

it seems that your module is trying to make some files changes before installing the postfix package (in charge of creating /etc/postfix).

Thanks in advance,

Best regards, Adam.

**Comment by thias** [comment]
This is probably happening with an old-ish release. The git code as well as today's Forge release of 0.3.4 should have this fixed with the `require => Package[$::postfix::params::postfix_package]` for any `postfix::file`.
